### ISSUE TITLE
Error Connecting to Azure IoT Central 

### ISSUE THREAD

**Issue by AronAyub** [edgeimpulse/workshop-fomo-azure-counter#1]
Hey Shawn, and edgeimpulse team,  I'm doing a project on bag counting and first thing I decided to use this example. On running the Arduino code, my ESP32 connects to the WIFI network but experiences a stuck on the boot loop as shown in the logs, any thoughts ? 
Please note that the board I'm using is ESP-WROOM32 just as the one you were using in the video.
Just wondering if it is an issue associated with pseudo static RAM ? but how was Shawn able to run same code in his EPS-WROMM32 ?
 

22:47:08.275 -> 2023/4/15 19:47:22 [INFO] Time initialized!
22:47:08.275 -> 2023/4/15 19:47:22 [INFO] Azure IoT client initialized (state=2)
22:47:09.198 -> ets Jun  8 2016 00:22:57
22:47:09.198 -> 
22:47:09.198 -> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
22:47:09.198 -> configsip: 0, SPIWP:0xee
22:47:09.198 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
22:47:09.198 -> mode:DIO, clock div:1
22:47:09.198 -> load:0x3fff0030,len:1344
22:47:09.198 -> load:0x40078000,len:13836
22:47:09.198 -> load:0x40080400,len:3608
22:47:09.198 -> entry 0x400805f0
22:47:09.519 -> 2023/4/15 19:47:23 [INFO] Connecting to WIFI wifi_ssid SS
22:47:10.158 -> ...
22:47:11.136 -> 2023/4/15 19:47:25 [INFO] WiFi connected, IP address: 192.168.43.141
22:47:11.182 -> 2023/4/15 19:47:25 [INFO] Setting time using SNTP
22:47:11.182 -> 
22:47:11.182 -> 2023/4/15 19:47:25 [INFO] Time initialized!
22:47:11.182 -> 2023/4/15 19:47:25 [INFO] Azure IoT client initialized (state=2)
22:47:12.057 -> ets Jun  8 2016 00:22:57
22:47:12.057 -> 
22:47:12.057 -> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
22:47:12.057 -> configsip: 0, SPIWP:0xee
22:47:12.057 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
22:47:12.103 -> mode:DIO, clock div:1
22:47:12.103 -> load:0x3fff0030,len:1344
22:47:12.103 -> load:0x40078000,len:13836
22:47:12.103 -> load:0x40080400,len:3608
22:47:12.103 -> entry 0x400805f0
22:47:12.384 -> 2023/4/15 19:47:26 [INFO] Connecting to WIFI wifi_ssid SS
22:47:13.031 -> ..........
22:47:17.516 -> 2023/4/15 19:47:31 [INFO] WiFi connected, IP address: 192.168.43.141
22:47:17.516 -> 2023/4/15 19:47:31 [INFO] Setting time using SNTP
22:47:17.562 -> 
22:47:17.562 -> 2023/4/15 19:47:31 [INFO] Time initialized!
22:47:17.562 -> 2023/4/15 19:47:31 [INFO] Azure IoT client initialized (state=2)
22:47:18.443 -> ets Jun  8 2016 00:22:57
22:47:18.443 -> 
22:47:18.443 -> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
22:47:18.443 -> configsip: 0, SPIWP:0xee
22:47:18.443 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
22:47:18.443 -> mode:DIO, clock div:1
22:47:18.443 -> load:0x3fff0030,len:1344
22:47:18.443 -> load:0x40078000,len:13836
22:47:18.443 -> load:0x40080400,len:3608
22:47:18.443 -> entry 0x400805f0
22:47:18.762 -> 2023/4/15 19:47:32 [INFO] Connecting to WIFI wifi_ssid SS
22:47:19.412 -> .
22:47:19.412 -> 2023/4/15 19:47:33 [INFO] WiFi connected, IP address: 192.168.43.141
22:47:19.412 -> 2023/4/15 19:47:33 [INFO] Setting time using SNTP
22:47:19.412 -> 
22:47:19.412 -> 2023/4/15 19:47:33 [INFO] Time initialized!
22:47:19.412 -> 2023/4/15 19:47:33 [INFO] Azure IoT client initialized (state=2)
22:47:20.296 -> ets Jun  8 2016 00:22:57
22:47:20.296 -> 
22:47:20.296 -> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
22:47:20.341 -> configsip: 0, SPIWP:0xee
22:47:20.341 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
22:47:20.341 -> mode:DIO, clock div:1
22:47:20.341 -> load:0x3fff0030,len:1344
22:47:20.341 -> load:0x40078000,len:13836
22:47:20.341 -> load:0x40080400,len:3608
22:47:20.341 -> entry 0x400805f0
22:47:20.667 -> 2023/4/15 19:47:34 [INFO] Connecting to WIFI wifi_ssid SS
22:47:21.279 -> ......
22:47:23.788 -> 2023/4/15 19:47:37 [INFO] WiFi connected, IP address: 192.168.43.141
22:47:23.788 -> 2023/4/15 19:47:37 [INFO] Setting time using SNTP
22:47:23.788 -> 
22:47:23.788 -> 2023/4/15 19:47:37 [INFO] Time initialized!
22:47:23.788 -> 2023/4/15 19:47:37 [INFO] Azure IoT client initialized (state=2)
22:47:24.703 -> ets Jun  8 2016 00:22:57
22:47:24.703 -> 
22:47:24.703 -> rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
22:47:24.703 -> configsip: 0, SPIWP:0xee
22:47:24.703 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
22:47:24.703 -> mode:DIO, clock div:1
22:47:24.703 -> load:0x3fff0030,len:1344
22:47:24.703 -> load:0x40078000,len:13836
22:47:24.703 -> load:0x40080400,len:3608
22:47:24.703 -> entry 0x400805f0
22:47:25.029 -> 2023/4/15 19:47:39 [INFO] Con

**Comment by AronAyub** [comment]
solved the above errror, you need to use a compatible board, was RAM related issue. If you are using any other ESP32 WROOM then select esp32 feather board. However i have another error as below:

The device provisions in Azure IoT Central application but shows like **Espressif ESP32 Azure IoT Kit,** also i receive an errors in the code as below:
It keeps iterating :
1:46:27.245 -> 2023/5/28 18:46:52 [ERROR] esp_tls_stack_err=0; esp_tls_cert_verify_flags=0;esp_transport_sock_errno=0;error_type=2;connect_return_code=3
21:46:27.245 -> 2023/5/28 18:46:52 [ERROR] connect_return_code=MQTT_CONNECTION_REFUSE_SERVER_UNAVAILABLE
21:46:27.245 -> E (241386) MQTT_CLIENT: MQTT connect failed
21:46:27.245 -> 2023/5/28 18:46:52 [INFO] MQTT client disconnected.
21:46:42.245 -> 2023/5/28 18:47:07 [INFO] MQTT client connecting.
21:46:44.106 -> 2023/5/28 18:47:08 [ERROR] MQTT client in ERROR state.
21:46:44.106 -> 2023/5/28 18:47:08 [ERROR] esp_tls_stack_err=0; esp_tls_cert_verify_flags=0;esp_transport_sock_errno=0;error_type=2;connect_return_code=3
21:46:44.152 -> 2023/5/28 18:47:08 [ERROR] connect_return_code=MQTT_CONNECTION_REFUSE_SERVER_UNAVAILABLE
21:46:44.152 -> E (258280) MQTT_CLIENT: MQTT connect failed
21:46:44.152 -> 2023/5/28 18:47:08 [INFO] MQTT client disconnected.
21:46:59.133 -> 2023/5/28 18:47:23 [INFO] MQTT client connecting.
21:47:00.891 -> 2023/5/28 18:47:25 [ERROR] MQTT client in ERROR state.
21:47:00.938 -> 2023/5/28 18:47:25 [ERROR] esp_tls_stack_err=0; esp_tls_cert_verify_flags=0;esp_transport_sock_errno=0;error_type=2;connect_return_code=3
21:47:00.938 -> 2023/5/28 18:47:25 [ERROR] connect_return_code=MQTT_CONNECTION_REFUSE_SERVER_UNAVAILABLE
21:47:00.938 -> E (275074) MQTT_CLIENT: MQTT connect failed
21:47:00.938 -> 2023/5/28 18:47:25 [INFO] MQTT client disconnected.
21:47:15.912 -> 2023/5/28 18:47:40 [INFO] MQTT client connecting.
21:47:17.715 -> 2023/5/28 18:47:42 [ERROR] MQTT client in ERROR state.
21:47:17.715 -> 2023/5/28 18:47:42 [ERROR] esp_tls_stack_err=0; esp_tls_cert_verify_flags=0;esp_transport_sock_errno=0;error_type=2;connect_return_code=3
21:47:17.715 -> 2023/5/28 18:47:42 [ERROR] connect_return_code=MQTT_CONNECTION_REFUSE_SERVER_UNAVAILABLE
21:47:17.715 -> E (291870) MQTT_CLIENT: MQTT connect failed
21:47:17.715 -> 2023/5/28 18:47:42 [INFO] MQTT client disconnected.

**Comment by ShawnHymel** [comment]
Hi @AronAyub,

This appears to be an error with the MQTT comms on the Azure side. I recommend trying to run the basic demos in the Azure library first (https://github.com/Azure/azure-sdk-for-c-arduino). If those do not work, you should file an issue with the repo there, as Microsoft maintains that library.

**Comment by AronAyub** [comment]
Hi @ShawnHymel , thank you, will definitely retry it. 

Was wondering, once your ESP feather provisions on IoT central, does it resume **Espressif ESP32 Azure IoT Kit** properties ?, because immediately it provisions, it shows as Espresssif ESP32 Azure IoT Kit resuming all the properties associated with the kit. This is despite redefining my device properties in IoT Central with only two properties, num_crews and num_washers:

**Comment by ShawnHymel** [comment]
Hi @AronAyub,

From what I remember, yes, the firmware runs the rest of the Microsoft demo code. I merely hacked the demo to add the two properties: `num_screws` and `num_washers`. Everything else is still there.

**Comment by AronAyub** [comment]
Hi @ShawnHymel,
Thank you. It's quite strange why my device fails, haha, everything else works fine. Just a few questions and then we close this up, please answer me to help figure out. My end goal is to build an industrial IIOT/AI counter MVP, and thanks for your 2 courses, I did them last year, they have really helped me. [_Whoever is reading this and is interested in Embedded AI, go in Coursera and find Shawn's 2 courses._](https://www.coursera.org/learn/introduction-to-embedded-machine-learning/home/week/1)

Here are the questions .

From your previous message, does it mean `num_screws `and `num_washers` properties takes some of  **Espressif ESP32 Azure IoT Kit** properties ? Then you later re-edited it in Azure IoT Central template ? 

OR you created a new device in Azure IoT central with entirely _**new components**_ and **new properties ?**

**Comment by ShawnHymel** [comment]
Hi @AronAyub,

You'll have to forgive me, as my memory is a bit fuzzy on how exactly I set this up. I created the demo over a year ago, and we only just filmed about a month ago. IIRC, I cloned the ESP32 Kit device in IoT Central, and I added `num_screws` and `num_washers` as custom properties. Let me know if that works for you!

**Comment by AronAyub** [comment]
Hi @ShawnHymel, thank you for the hands-on. I figured it out. 
I had to use the esp8266 dev board after the esp32 failed several times. This was a significant milestone for what I was creating. Thank you again, let me close this for now.

![image](https://github.com/edgeimpulse/workshop-fomo-azure-counter/assets/55284959/ff58a3e7-2773-45ce-8bfe-b609d01d255d)

See the above ^^
